name: Terraform-Plan-AWS-Infra

on: 
  push:
    branches:
      - main

jobs:
  terraform-configure:
    name: terraform
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: 'us-east-1'

      - name: Terraform Init
        id: Init
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan  


